### ISSUE TITLE
Port Issue: UFO 50 - No Audio New 12/7 Update for 1.4.2 Version

### ISSUE THREAD

**Issue by Darky2k1** [PortsMaster/PortMaster-New#1025]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [ ] Other device (device name here)
* [ X] All of the above

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] RockNix
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA
* [ X] Unknown - Raspberry Pi 5 Using Batocera

#### Description
No Audio - When After Patch on 1.4.2 - Using the newest build

#### Reproduction Steps
Use Portmaster to Patch 1.4.2 with the patch from 12/7/24 - No Audio

Version 1.3.1 works fine (Previously released version)

**Comment by JeodC** [comment]
RPi5 using Batocera is not officially supported by us. In addition, please come to our Discord for minor assistance like this.

**Comment by Darky2k1** [comment]
Just so you have more info on the problem - [1316692281721360425](https://discord.com/channels/1122861252088172575/1316692281721360425)
