### ISSUE TITLE
[Documentation/Tooling] tools/build_release.py expects gameinfo.xml, but documentation lists this file as optional

### ISSUE THREAD

**Issue by TarkanAl-Kazily** [PortsMaster/PortMaster-New#1086]
The documentation in the README indicates that these are the required files in a new port:

>  Each port must have a port.json, screenshot.{jpg,png}, README.md, a port script and a port directory.

These are optional files, including `gameinfo.xml`:

> It may optionally include a cover.{jpg,png} and a gameinfo.xml.

When running `python3 tools/build_release.py --do-check` on my port containing the following files:

```
nottetris2/
Nottetris2.sh*
port.json
README.md
screenshot.jpg
```

I get an error detecting my port:
```
Bad port nottetris2
- Errors:
  Missing gameinfo.xml.
```

Can the documentation or the tool be updated to accurately reflect the required files?

**Comment by Cebion** [comment]
> The documentation in the README indicates that these are the required files in a new port:
> 
> > Each port must have a port.json, screenshot.{jpg,png}, README.md, a port script and a port directory.
> 
> These are optional files, including `gameinfo.xml`:
> 
> > It may optionally include a cover.{jpg,png} and a gameinfo.xml.
> 
> When running `python3 tools/build_release.py --do-check` on my port containing the following files:
> 
> ```
> nottetris2/
> Nottetris2.sh*
> port.json
> README.md
> screenshot.jpg
> ```
> 
> I get an error detecting my port:
> 
> ```
> Bad port nottetris2
> - Errors:
>   Missing gameinfo.xml.
> ```
> 
> Can the documentation or the tool be updated to accurately reflect the required files?

Probably missed a spot. Our main packaging guide is this one.

https://portmaster.games/packaging.html#new-port-structure
Where the only optional thing is cover.jpg/png

I'll update the main readme to reflec those changes

**Comment by Cebion** [comment]
https://github.com/PortsMaster/PortMaster-New/commit/a0cd16dfc7f9671984fbe44dea2baeab013d0ff3
