### ISSUE TITLE
2x PortMaster entries

### ISSUE THREAD

**Issue by lauren7ino** [PortsMaster/PortMaster-New#193]
Hi
In ArkOS Emulation Station menu I had one entry in the Options menu with the name "PortMaster".
Then I auto-updated PortMaster in ArkOS, and now the Options menu has 2x "PortMaster" entries.

PORTMASTER
_ CONFIG
_ _ PORTMASTER
PORTMASTER

Christian Haitian from ArkOS says this is the correct place to report this.
Thanks

**Comment by lauren7ino** [comment]
I followed your instructions:
I install your PortMaster, I restart Emulation Station, and it seems to be fixed -> Only one PortMaster menu entry in Emulation Station. Good!

Then,
I start the PortMaster, it detects a new version, downloads, I restart Emulation Station, and the double PortMaster menu returns.
Not good.

Sorry for my basic English.

**Comment by kloptops** [comment]
Hi @lauren7ino it turns out there was a bug in the Install.PortMaster.sh script generation. I have just released a new one which if you run will fix your issues.

https://github.com/PortsMaster/PortMaster-GUI/releases/download/2024.03.20-1013/Install.PortMaster.sh

Sorry for any inconvenience 😄

**Comment by lauren7ino** [comment]
Hi! It works.
This version doesn't detect new updates, so let's see if it's still fixed next time it updates PortMaster.
It dumps a lot of (debugging?) messages when changing themes/colors. Otherwise seems fine.
Thanks

**Comment by kloptops** [comment]
Yeah it will be fine next time it updates. 🤞

One day i will clean up the debugging info, but for now it's not hurting anyone. 😄 

Glad this could be sorted!
