### ISSUE TITLE
Port Issue: OpenLara

### ISSUE THREAD

**Issue by lauren7ino** [PortsMaster/PortMaster-New#194]
Hi all,
Sorry my basic English.
I installed on an Anbernic RG353M on ArkOS PortMaster the Tomb Raider 1 game.
Added the missing files and everything runs perfectly and smoothly.
The problem: I can't find a way to Save the game progress.
The menu only contais Load Game|New Game|Exit Game.
There is also no Save Crystals (I can't find any), so the question is:
How can I save the game progress?
What am I missing? 
Am I using the incorrect files?
Thank you in advance,
Keep up the good work!

**Comment by Cebion** [comment]
Have you checkted the OpenLara  Website / Repo for Game information?

**Comment by kloptops** [comment]
Hi @lauren7ino 

Probably best to jump onto the [PortMaster discord](https://discord.gg/JxYBp9HTAY) for port help. 

as for openlara it is a very old port that uses the older `oga_controls`. It looks like load and save is mapeed to '5' & '9', i am not sure how this handled in this game.

**Comment by lauren7ino** [comment]
Hi 
Thank you for the support. I will try to map these keys the device ... somehow?
I originally posted this same question here (https://github.com/XProger/OpenLara/issues/487), but obtained no answer.
If everything fails, I'll probably go with the PS1 version.
Thanks

**Comment by mhoogcarspel** [comment]
Save crystals are there, when you do find one, make sure you don't have your pistols equipped, face it and press the use button (A, which is also shoot). The game also saves at the end of each level.
