### ISSUE TITLE
Port Issue: Daikatana

### ISSUE THREAD

**Issue by tnt10512** [PortsMaster/PortMaster-New#197]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [ ] Other device (device name here)
* [ ] All of the above

### Firmware

* [x] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA

**Comment by tnt10512** [comment]
Daikatana

Port will not run, no errors.  Followed instructions as presented in [Portmaster games](https://portmaster.games/detail.html?name=daikatana).  Took files directly from the CD Data folder and placed in GameData folder

Below is the log file from my SD card2. I took the gamedata files direct from my CD. Am I missing something else that the wiki doesn't disclose?
----- Filesystem Initialization -----
Current search path:
/home/ark/.local/share/./Daikatana/gamedata
/roms2/ports/daikatana/gamedata
/roms2/ports/daikatana/gamedata/pak4.pak (792 files)
/roms2/ports/daikatana/gamedata/pak3.pak (782 files)
/roms2/ports/daikatana/gamedata/pak2.pak (83 files)
/home/ark/.local/share/./Daikatana/data
/roms2/ports/daikatana/data
1657 files in PAK files

Unknown command "vid_restart"
Unknown command "snd_restart"
couldn't exec daikatana.cfg
execing curcfg.cfg
Could not find or load /home/ark/.local/share/./Daikatana/gamedata/current.cfg. Reason: No such file or directory. Using defaults!
execing daikatana13.cfg
couldn't exec default_keys.cfg
execing gamecontroller.cfg
couldn't exec default_keys.cfg
Verifying official game PAK files...

**Comment by Cebion** [comment]
Hi,

Probably best to jump onto the [PortMaster discord](https://discord.gg/JxYBp9HTAY) for port help.

**Comment by mhoogcarspel** [comment]
looks like you're missing pak1.pak, I only have the steam version but that looks like this:

```
----- Filesystem Initialization -----
Current search path:
/storage/.local/share/./Daikatana/gamedata
/storage/roms/ports/daikatana/gamedata
/storage/roms/ports/daikatana/gamedata/pak4.pak (792 files)
/storage/roms/ports/daikatana/gamedata/pak3.pak (782 files)
/storage/roms/ports/daikatana/gamedata/pak2.pak (83 files)
/storage/roms/ports/daikatana/gamedata/pak1.pak (11455 files)
----------
/storage/.local/share/./Daikatana/data
/storage/roms/ports/daikatana/data
-------------------------------------
13112 files in PAK files

Unknown command "vid_restart"
Unknown command "snd_restart"
couldn't exec daikatana.cfg
execing daikatana13.cfg
couldn't exec default_keys.cfg
execing gamecontroller.cfg
couldn't exec default_keys.cfg
Verifying official game PAK files... OK!
...
```

**Comment by tnt10512** [comment]
Thanks for the input of the pak file, I made sure all files were in place and the program still doesn't run on the handheld but plays fine on my pc.  Took the files from the working data folder and copied them to the gamedata folder.  This is the only log, not very useful.

----- Filesystem Initialization -----
Current search path:
/home/ark/.local/share/./Daikatana/gamedata
/roms2/ports/daikatana/gamedata
/roms2/ports/daikatana/gamedata/pak6.pak (65 files)
/roms2/ports/daikatana/gamedata/pak5.pak (5634 files)
/roms2/ports/daikatana/gamedata/pak4.pak (792 files)
/roms2/ports/daikatana/gamedata/pak3.pak (782 files)
/roms2/ports/daikatana/gamedata/pak2.pak (83 files)
/roms2/ports/daikatana/gamedata/pak1.pak (11449 files)
----------
/home/ark/.local/share/./Daikatana/data
/roms2/ports/daikatana/data
-------------------------------------
18805 files in PAK files

Unknown command "vid_restart"
Unknown command "snd_restart"
couldn't exec daikatana.cfg
execing curcfg.cfg
Could not find or load /home/ark/.local/share/./Daikatana/gamedata/current.cfg.  Reason: No such file or directory.  Using defaults!
execing daikatana13.cfg
couldn't exec default_keys.cfg
execing gamecontroller.cfg
couldn't exec default_keys.cfg
Verifying official game PAK files...

**Comment by JohnnyonFlame** [comment]
> Thanks for the input of the pak file, I made sure all files were in place and the program still doesn't run on the handheld but plays fine on my pc. Took the files from the working data folder and copied them to the gamedata folder. This is the only log, not very useful.
> ## ----- Filesystem Initialization -----
> Current search path:
> /home/ark/.local/share/./Daikatana/gamedata
> /roms2/ports/daikatana/gamedata
> /roms2/ports/daikatana/gamedata/pak6.pak (65 files)
> /roms2/ports/daikatana/gamedata/pak5.pak (5634 files)
> /roms2/ports/daikatana/gamedata/pak4.pak (792 files)
> /roms2/ports/daikatana/gamedata/pak3.pak (782 files)
> /roms2/ports/daikatana/gamedata/pak2.pak (83 files)
> /roms2/ports/daikatana/gamedata/pak1.pak (11449 files)
> ## /home/ark/.local/share/./Daikatana/data
> /roms2/ports/daikatana/data
> 
> 18805 files in PAK files
> 
> Unknown command "vid_restart" Unknown command "snd_restart" couldn't exec daikatana.cfg execing curcfg.cfg Could not find or load /home/ark/.local/share/./Daikatana/gamedata/current.cfg. Reason: No such file or directory. Using defaults! execing daikatana13.cfg couldn't exec default_keys.cfg execing gamecontroller.cfg couldn't exec default_keys.cfg Verifying official game PAK files...

The Daikatana port is based off of DK1.3, You need to update to DK1.2 and then copy the data files.

**Comment by JohnnyonFlame** [comment]
An issue was found on the package due to a regression caused by a Portmaster restructuring, please see if updating the port fixes this for you.

**Comment by tnt10512** [comment]
Read your post and reloaded Daikatana.  It did not work but I will re configure my files since I have made many changes trying to get this to work. I will start fresh and let you know.

Thanks for the update

Dana
________________________________
