### ISSUE TITLE
Port Issue: Bleed

### ISSUE THREAD

**Issue by 25minutes** [PortsMaster/PortMaster-New#251]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [ ] Other device (device name here)
* [ ] All of the above

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA

**Comment by 25minutes** [comment]
Description:

bleed fails to run because patch cannot complete successfully. In gamedate folder, MMHOOK_Bleed.dll has been generated successfully, but MONOMODDED_Bleed.exe is not.

install_log.txt shows error:
MonoMod.Utils.RelinkTargetNotFoundException: MonoMod cannot map dependency MMHOOK_Bleed.dll -> ((Microsoft.Xna.Framework.Game, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553), (Microsoft.Xna.Framework.Game)) - not found

This is strange, as MMHOOK_Bleed.dll is already in gamedate folder. Environment varible or path issue?

Both install_log.txt & log.txt are attached.
[install_log.txt](https://github.com/PortsMaster/PortMaster-New/files/14820020/install_log.txt)
[log.txt](https://github.com/PortsMaster/PortMaster-New/files/14820021/log.txt)

Reproduction Steps:
Simply copy bleed files from steam copy to gamedate folder, and try to launch it.

**Comment by mhoogcarspel** [comment]
The Windows version of the files won't work, you will need the Linux version.

I don't have the steam version to test, but hopefully this works (we can add this to the description if this tests ok)

To get the Linux version from Steam on Windows:

- Press <Windows key>+R 
- Type/paste in: `steam://open/console`
You should have steam open with CONSOLE on top, and a text box at the bottom
- Type/paste in the textbox: `download_depot 239800 239803`  
When the download is complete, it will tell you the location of the folder in the console, it doesn't show as a normal download
- Copy all files from that directory to `/ports/bleed/gamedata`
