### ISSUE TITLE
Port Issue: 

### ISSUE THREAD

**Issue by faux123** [PortsMaster/PortMaster-New#274]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [x] X55
* [ ] Other device (device name here)
* [ ] All of the above

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [x] JelOS
* [ ] RockNix
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA

### Port: {Port Name}
Super Meat Boy

#### Description

Black screen upon launching

#### Reproduction Steps

Install the game, copy over Steam Compatibility version, start the game from ports and will encounter black screen.
attached is the log.txt.  From the reading it's complaining about not able to access OpenAL device on the X55
[log.txt](https://github.com/PortsMaster/PortMaster-New/files/14921089/log.txt)

**Comment by Cebion** [comment]
That is unfortunate an os problem. Check the Jelos wiki for sounds problems
