### ISSUE TITLE
Port Issue: Balatro missing libs

### ISSUE THREAD

**Issue by etienne72230** [PortsMaster/PortMaster-New#310]
### Device Type

* [x] Trimui Smart Pro

### Firmware

* [x] Trimui 1.0.4

#### Description

Missing lib in folder balatro/libs.aarch64 :

`- ./bin/love.aarch64: error while loading shared libraries: libcairo.so.2: cannot open shared object file: No such file or directory`

list of missing libs :
- libcairo.so.2
- libxcb-shm.so.0
- libxcb.so.1
- libxcb-render.so.0
- libXrender.so.1
- libX11.so.6
- libXext.so.6
- libXau.so.6
- libXdmcp.so.6
- libbsd.so.0

after adding this libs a new error occure :
`./bin/love.aarch64: symbol lookup error: /mnt/SDCARD/ports/balatro/libs.aarch64/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates`

#### Reproduction Steps

1. In file Balatro.sh uncomment line 31 

`exec > >(tee "$GAMEDIR/log.txt") 2>&1`

2. run balatro 
3. check log file in ports/balatro/log.txt
4. I try to add missing libs from an others port (ports/sonic.cd/soniccd/libs)

**Comment by JanTrueno** [comment]
Try removing libtheoradec instead of adding libs.

**Comment by Cebion** [comment]
TrimUI is not officially supported as of yet. 
There is a WIP build out there.

**Comment by etienne72230** [comment]
problem solved by removing lib libtheoradec in folder libs.aarch64.
