### ISSUE TITLE
Port Issue:  Carmageddon

### ISSUE THREAD

**Issue by madebr** [PortsMaster/PortMaster-New#423]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [ ] Other device (device name here)
* [x] All of the above

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] RockNix
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA

### Port: {Port Name}

Carmageddon
https://portmaster.games/detail.html?name=carmageddon

#### Description

Hello, The Carmageddon port is based on dethrace, which uses the GPL-3 license.
This license requires ports and modifications to provide their modifications in source archive.
I cannot find a (download) link with those modifications on [portmaster's site](https://portmaster.games/detail.html?name=carmageddon).

#### Reproduction Steps
n/a

**Comment by Cebion** [comment]
I'm sorry you are correct the license files seem to be missing on this port.
We're really careful that we always include license files and compile history and from where the package was built.

This was merged on the old portmater repo before we had our strict checks
https://github.com/christianhaitian/PortMaster/pull/252

There was also an inquiry to the porter from which version he built.
https://discord.com/channels/1122861252088172575/1157962888305180713/1211880004774924330

He built it from this fork
https://github.com/orsonmmz/dethrace/tree/gles

I'll upload the License asap and point to the fork he built it from as well.

**Comment by Cebion** [comment]
Files got added

https://github.com/PortsMaster/PortMaster-New/commit/b53d3cc464bc714ab5a368ac0dd3a0088725a8e0
https://github.com/PortsMaster/PortMaster-New/commit/9763f2e256bf2edad475d4f61bc6cce6806d75b6

I hope it's okay now.
Any questions you can also always reach us on our discord as well.

**Comment by madebr** [comment]
Thanks! I appreciate the quick fix!
