### ISSUE TITLE
Port Issue: To the moon RG35XX H

### ISSUE THREAD

**Issue by orenigittigitt** [PortsMaster/PortMaster-New#474]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [ ] Other device (device name here)
* [ ] All of the above
* [X ] RG35XX H

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] RockNix
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA
* [ X] MuOS

### Port: {Port Name}
To the Moon
#### Description

 German umlauts do not work because of a misconfig in mkxp.conf (New Times Roman instead of Times New Roman). To improve text speed significantly conf should be set to:

../ports/to_the_moon/config/mkxp.conf:

fullscreen=true
winResizable=false
anyAltToggleFS=true
smoothScaling=false
vsync=true
subImageFix=false
enableBlitting=false
frameSkip=false

# DO NOT TOUCH
iconPath=icon.png
dataPathOrg=freebirdgames
dataPathApp=tothemoon
RTP=Audio.dat
RTP=lang.dat
preloadScript=mkxp/preload/ruby18_comp.rb
preloadScript=mkxp/preload/win32_wrap.rb
preloadScript=mkxp/preload/utils.dll.rb
fontSub=Arial>Open Sans
fontSub=Times New Roman>Open Sans

**Comment by dxdatabase** [comment]
Thanks, fix french language too. (éàèç not displaying).
