### ISSUE TITLE
PortMaster GUI: Shuffled button layout on Powkiddy X55

### ISSUE THREAD

**Issue by takagiy** [PortsMaster/PortMaster-New#508]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [x] X55
* [ ] Other device (device name here)
* [ ] All of the above

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA
* [x] ROCKNIX (20240612)

### GUI Track
* [x] Release
* [ ] Beta

### Description

The UI indicates that A for confirmaion and B for cancel.

![IMG_2863](https://github.com/PortsMaster/PortMaster-New/assets/18656090/136e4bc9-9106-4983-b9fd-6a293cd5f83a) ![IMG_2864](https://github.com/PortsMaster/PortMaster-New/assets/18656090/ddfc676c-6b51-4bd7-8f99-a98abd73f0de)

But the actual inputs are inverted so I have to press B to confirm and A to back. (X is properly mapped to X.)
It's confusing.

### Reproduction Steps

1. Boot the device.
2. Open tools > PortMaster.
3. -> PortMaster-GUI opens.
4. Press A.
5. -> It asks you "Are you sure you want to exit PortMaster? A: Okay B: Cancel"
6. Press B.
7. -> PortMaster-GUI quits.

**Comment by Cebion** [comment]
This is a bug In the OS, it worked before. Make sure to start PM from tools. In doubt delete the PM folder and start it again from tools.
