### ISSUE TITLE
Port Issue: Mable in the Woods

### ISSUE THREAD

**Issue by stephen-hill** [PortsMaster/PortMaster-New#574]
### Device Type
* [x] RGB30

### Firmware
* [x] ArkOS

#### Description
Stops loading at a splash screen.

#### Reproduction Steps

- Install latest port
- Copy game.unx to gamedata from Gog Linux version 1.7
- Run the game

### log.txt
[log.txt](https://github.com/user-attachments/files/16469447/log.txt)

**Comment by tabreturn** [comment]
This port was never tested with the GOG version, so it's quite possible that doesn't work. 

See: https://portmaster.games/detail.html?name=mableandthewood

*You can purchase Mable and the Wood at: https://graffiti-games.itch.io/mable-and-the-wood. Download the Linux version and extract it, and place the game.unx file in the port's gamedata directory. Tested using Mable_Linux_v4.zip version 4 (Oct 03, 2019).*

**Comment by JeodC** [comment]
`ports/gmloader/libyoyo.c:160: Memory allocation failed: Attempting to allocate 4294967295 bytes`

This seems to suffer from the same kind of problem Sonic Triple Trouble did. If there are newer versions out there, they may be able to run via gmloader-next. You can always suggest this in the discord or on the website.

**Comment by tabreturn** [comment]
When the game patches, it fixes the memory issue. For the patch to apply, one must use the correct game version -- the OP has used GOG (not itch.io).
