### ISSUE TITLE
Port Issue: Cave Story Evo on Trimui Smart missing libs

### ISSUE THREAD

**Issue by Windstarry** [PortsMaster/PortMaster-New#587]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [x] Other device (Trimui Smart Pro)
* [ ] All of the above

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] RockNix
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA
* [x] Trimui 1.0.4

### Port: {Port Name}
Cave Story Evo
#### Description

Missing lib in folder nxengine-evo

#### Reproduction Steps

1. add  exec > >(tee "$GAMEDIR/log.txt") 2>&1 In file launch.sh
2. run game
3. check log file in ports/nxengine-evo/log.txt
./nxengine-evo: error while loading shared libraries: libpng16.so.16

**Comment by JeodC** [comment]
The cfw (crossmix in this case I assume) will need to provide that library. It's included with every other cfw.
