### ISSUE TITLE
Port Issue: Ion Fury install instructions for Steam version incorrect

### ISSUE THREAD

**Issue by buckysrevenge** [PortsMaster/PortMaster-New#869]
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [ ] Other device (device name here)
* [x] All of the above

### Firmware

* [ ] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] RockNix
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA

#### Description

The instructions in the README.md state to use the Steam console command "download_depot 562860 562861 8506993987461859820", but this does not download all of the necessary files to run the game with PortMaster. The file fury.def is not in this version of the game, it was removed over 4 years ago. The last manifest that included the game is 189007903929408028, so the instructions should be updated to "download_depot 562860 562861 189007903929408028"
#### Reproduction Steps

Steps to reproduce: Open the Steam console and run the command "download_depot 562860 562861 8506993987461859820", the download directory is missing fury.def

**Comment by cdeletre** [comment]
Fixed in PR # [870](https://github.com/PortsMaster/PortMaster-New/pull/870)
